spring:
  application:
    name: coffee-shop
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5432/cf_db
    username: postgres
    password: root
  liquibase:
    change-log: classpath:/db/changelog-master.xml
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: none
    properties:
      hibernate:
        connection:
          pool_size: 10
        enhancer:
          enableAssociationManagement: false
          enableDirtyTracking: false
          enableLazyInitialization: false
        jdbc:
          batch_size: 3
        show_sql: true
        format_sql: true
        highlight_sql: true

      jakarta:
        persistence:
          jdbc:
            password: root
            url: jdbc:postgresql://localhost:5432/cf_db
            user: postgres

app:
  root-path: /apis/v1
  shop-id: cd3fe1f2-4167-4e30-bbc3-4fabaeef87cd
  queues:
    - bda05e7d-65c5-4988-b0b3-d70f261227cb
    - 8742faff-83d2-4c1c-a423-e2f4dfd8ae8b
#    - ecf82964-b501-4885-8c4a-0d781b169199

springdoc:
  api-docs:
    path: /v3/swagger-ui.html
  swagger-ui:
    path: /v3/api-docs
