spring:
  application:
    name: coffee-shop
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: root

app:
  root-path: /apis/v1
  shop-id: cd3fe1f2-4167-4e30-bbc3-4fabaeef87cd
  queues:
    - bda05e7d-65c5-4988-b0b3-d70f261227cb
    - 8742faff-83d2-4c1c-a423-e2f4dfd8ae8b
#    - ecf82964-b501-4885-8c4a-0d781b169199
